import { FileText, ShoppingCart, ClipboardList, PackageCheck, Receipt, Wallet, Landmark, RotateCcw, Undo2, CircleDollarSign } from 'lucide-react';
import { ROUTES } from '../../../app/constants/routes.js';
import { endpoints } from '../../../shared/api/endpoints.js';
import { PERMISSIONS } from '../../../app/constants/permissions.js';

export const PHASE1_MODULES = {
  quotations: {
    key: 'quotations',
    type: 'quotation',
    title: 'Quotations',
    singular: 'Quotation',
    icon: FileText,
    routeList: ROUTES.quotations,
    routeNew: ROUTES.quotationNew,
    routeDetail: ROUTES.quotationDetail,
    permissionRead: PERMISSIONS.quotationRead,
    permissionManage: PERMISSIONS.quotationManage,
    permissionFinalize: PERMISSIONS.quotationIssue,
    permissionVoid: PERMISSIONS.quotationVoid,
    statusFinal: 'issued',
    finalActionLabel: 'Issue Quotation',
    amountSource: 'lines',
    partnerRole: 'customer',
    requirePartner: true,
    requireDueDate: false,
    requirePrimaryAccount: false,
    requireCashAccount: false,
    requireAmountTotal: false,
    extraFields: [],
    lineMode: 'postingLines',
    listQueryKey: 'quotations',
    detailQueryKey: 'quotation'
  },
  salesOrders: {
    key: 'salesOrders',
    type: 'salesOrder',
    title: 'Sales Orders',
    singular: 'Sales Order',
    icon: ShoppingCart,
    routeList: ROUTES.salesOrders,
    routeNew: ROUTES.salesOrderNew,
    routeDetail: ROUTES.salesOrderDetail,
    permissionRead: PERMISSIONS.salesOrderRead,
    permissionManage: PERMISSIONS.salesOrderManage,
    permissionFinalize: PERMISSIONS.salesOrderIssue,
    permissionVoid: PERMISSIONS.salesOrderVoid,
    statusFinal: 'issued',
    finalActionLabel: 'Issue Sales Order',
    amountSource: 'lines',
    partnerRole: 'customer',
    requirePartner: true,
    requireDueDate: true,
    lineMode: 'basicLines',
    listQueryKey: 'salesOrders',
    detailQueryKey: 'salesOrder'
  },
  purchaseRequisitions: {
    key: 'purchaseRequisitions',
    type: 'purchaseRequisition',
    title: 'Purchase Requisitions',
    singular: 'Purchase Requisition',
    icon: ClipboardList,
    routeList: ROUTES.purchaseRequisitions,
    routeNew: ROUTES.purchaseRequisitionNew,
    routeDetail: ROUTES.purchaseRequisitionDetail,
    permissionRead: PERMISSIONS.purchaseRequisitionRead,
    permissionManage: PERMISSIONS.purchaseRequisitionManage,
    permissionFinalize: PERMISSIONS.purchaseRequisitionIssue,
    permissionVoid: PERMISSIONS.purchaseRequisitionVoid,
    statusFinal: 'issued',
    finalActionLabel: 'Issue Requisition',
    amountSource: 'lines',
    requireDueDate: false,
    lineMode: 'basicLines',
    listQueryKey: 'purchaseRequisitions',
    detailQueryKey: 'purchaseRequisition'
  },
  purchaseOrders: {
    key: 'purchaseOrders',
    type: 'purchaseOrder',
    title: 'Purchase Orders',
    singular: 'Purchase Order',
    icon: ShoppingCart,
    routeList: ROUTES.purchaseOrders,
    routeNew: ROUTES.purchaseOrderNew,
    routeDetail: ROUTES.purchaseOrderDetail,
    permissionRead: PERMISSIONS.purchaseOrderRead,
    permissionManage: PERMISSIONS.purchaseOrderManage,
    permissionFinalize: PERMISSIONS.purchaseOrderIssue,
    permissionVoid: PERMISSIONS.purchaseOrderVoid,
    statusFinal: 'issued',
    finalActionLabel: 'Issue Purchase Order',
    amountSource: 'lines',
    partnerRole: 'vendor',
    requirePartner: true,
    requireDueDate: true,
    lineMode: 'basicLines',
    listQueryKey: 'purchaseOrders',
    detailQueryKey: 'purchaseOrder'
  },
  goodsReceipts: {
    key: 'goodsReceipts',
    type: 'goodsReceipt',
    title: 'Goods Receipts',
    singular: 'Goods Receipt',
    icon: PackageCheck,
    routeList: ROUTES.goodsReceipts,
    routeNew: ROUTES.goodsReceiptNew,
    routeDetail: ROUTES.goodsReceiptDetail,
    permissionRead: PERMISSIONS.goodsReceiptRead,
    permissionManage: PERMISSIONS.goodsReceiptManage,
    permissionFinalize: PERMISSIONS.goodsReceiptPost,
    permissionVoid: PERMISSIONS.goodsReceiptVoid,
    statusFinal: 'posted',
    finalActionLabel: 'Post Goods Receipt',
    amountSource: 'lines',
    requirePrimaryAccount: true,
    requireSourceDocument: true,
    partnerRole: 'vendor',
    lineMode: 'postingLines',
    listQueryKey: 'goodsReceipts',
    detailQueryKey: 'goodsReceipt'
  },
  expenses: {
    key: 'expenses',
    type: 'expense',
    title: 'Expenses',
    singular: 'Expense',
    icon: Receipt,
    routeList: ROUTES.expenses,
    routeNew: ROUTES.expenseNew,
    routeDetail: ROUTES.expenseDetail,
    permissionRead: PERMISSIONS.expenseRead,
    permissionManage: PERMISSIONS.expenseManage,
    permissionFinalize: PERMISSIONS.expensePost,
    permissionVoid: PERMISSIONS.expenseVoid,
    statusFinal: 'posted',
    finalActionLabel: 'Post Expense',
    amountSource: 'lines',
    requirePrimaryAccount: true,
    lineMode: 'postingLines',
    listQueryKey: 'expenses',
    detailQueryKey: 'expense'
  },
  pettyCash: {
    key: 'pettyCash',
    type: 'pettyCash',
    title: 'Petty Cash',
    singular: 'Petty Cash Voucher',
    icon: Wallet,
    routeList: ROUTES.pettyCash,
    routeNew: ROUTES.pettyCashNew,
    routeDetail: ROUTES.pettyCashDetail,
    permissionRead: PERMISSIONS.pettyCashRead,
    permissionManage: PERMISSIONS.pettyCashManage,
    permissionFinalize: PERMISSIONS.pettyCashPost,
    permissionVoid: PERMISSIONS.pettyCashVoid,
    statusFinal: 'posted',
    finalActionLabel: 'Post Petty Cash',
    amountSource: 'lines',
    requireCashAccount: true,
    lineMode: 'postingLines',
    listQueryKey: 'pettyCash',
    detailQueryKey: 'pettyCashItem'
  },
  advances: {
    key: 'advances',
    type: 'advance',
    title: 'Advances',
    singular: 'Advance',
    icon: Landmark,
    routeList: ROUTES.advances,
    routeNew: ROUTES.advanceNew,
    routeDetail: ROUTES.advanceDetail,
    permissionRead: PERMISSIONS.advanceRead,
    permissionManage: PERMISSIONS.advanceManage,
    permissionFinalize: PERMISSIONS.advancePost,
    permissionVoid: PERMISSIONS.advanceVoid,
    statusFinal: 'posted',
    finalActionLabel: 'Post Advance',
    amountSource: 'explicit',
    requireCashAccount: true,
    requirePrimaryAccount: true,
    requireAmountTotal: true,
    extraFields: [{ key: 'advanceType', label: 'Advance Type', type: 'select', options: [
      { value: 'customer', label: 'Customer' },
      { value: 'vendor', label: 'Vendor' },
      { value: 'staff', label: 'Staff' }
    ] }],
    lineMode: 'none',
    listQueryKey: 'advances',
    detailQueryKey: 'advance'
  },
  returns: {
    key: 'returns',
    type: 'return',
    title: 'Returns',
    singular: 'Return',
    icon: RotateCcw,
    routeList: ROUTES.returns,
    routeNew: ROUTES.returnNew,
    routeDetail: ROUTES.returnDetail,
    permissionRead: PERMISSIONS.returnRead,
    permissionManage: PERMISSIONS.returnManage,
    permissionFinalize: PERMISSIONS.returnPost,
    permissionVoid: PERMISSIONS.returnVoid,
    statusFinal: 'posted',
    finalActionLabel: 'Post Return',
    amountSource: 'lines',
    requirePartner: true,
    requireSourceDocument: true,
    extraFields: [{ key: 'returnType', label: 'Return Type', type: 'select', options: [
      { value: 'sales_return', label: 'Sales Return' },
      { value: 'purchase_return', label: 'Purchase Return' }
    ] }],
    lineMode: 'postingLines',
    listQueryKey: 'returns',
    detailQueryKey: 'returnItem'
  },
  refunds: {
    key: 'refunds',
    type: 'refund',
    title: 'Refunds',
    singular: 'Refund',
    icon: CircleDollarSign,
    routeList: ROUTES.refunds,
    routeNew: ROUTES.refundNew,
    routeDetail: ROUTES.refundDetail,
    permissionRead: PERMISSIONS.refundRead,
    permissionManage: PERMISSIONS.refundManage,
    permissionFinalize: PERMISSIONS.refundPost,
    permissionVoid: PERMISSIONS.refundVoid,
    statusFinal: 'posted',
    finalActionLabel: 'Post Refund',
    amountSource: 'explicit',
    requirePartner: true,
    requireCashAccount: true,
    requirePrimaryAccount: true,
    requireAmountTotal: true,
    extraFields: [{ key: 'refundType', label: 'Refund Type', type: 'select', options: [
      { value: 'customer_refund', label: 'Customer Refund' },
      { value: 'vendor_refund', label: 'Vendor Refund' }
    ] }],
    lineMode: 'none',
    listQueryKey: 'refunds',
    detailQueryKey: 'refund'
  }
};

Object.assign(PHASE1_MODULES.quotations, { endpoints: endpoints.modules.transactions.quotations });
Object.assign(PHASE1_MODULES.salesOrders, { endpoints: endpoints.modules.transactions.salesOrders });
Object.assign(PHASE1_MODULES.purchaseRequisitions, { endpoints: endpoints.modules.transactions.purchaseRequisitions });
Object.assign(PHASE1_MODULES.purchaseOrders, { endpoints: endpoints.modules.transactions.purchaseOrders });
Object.assign(PHASE1_MODULES.goodsReceipts, { endpoints: endpoints.modules.transactions.goodsReceipts });
Object.assign(PHASE1_MODULES.expenses, { endpoints: endpoints.modules.transactions.expenses });
Object.assign(PHASE1_MODULES.pettyCash, { endpoints: endpoints.modules.transactions.pettyCash });
Object.assign(PHASE1_MODULES.advances, { endpoints: endpoints.modules.transactions.advances });
Object.assign(PHASE1_MODULES.returns, { endpoints: endpoints.modules.transactions.returns });
Object.assign(PHASE1_MODULES.refunds, { endpoints: endpoints.modules.transactions.refunds });

export function getPhase1ModuleConfig(key) {
  return PHASE1_MODULES[key];
}
