import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useApi } from '../../../shared/hooks/useApi.js';
import { makeBankingApi } from '../api/banking.api.js';
import { PageHeader } from '../../../shared/components/layout/PageHeader.jsx';
import { ContentCard } from '../../../shared/components/layout/ContentCard.jsx';
import { Button } from '../../../shared/components/ui/Button.jsx';
import { Input } from '../../../shared/components/ui/Input.jsx';
import { Textarea } from '../../../shared/components/ui/Textarea.jsx';
import { Modal } from '../../../shared/components/ui/Modal.jsx';
import { useToast } from '../../../shared/components/ui/Toast.jsx';
import { ROUTES } from '../../../app/constants/routes.js';
function rowsOf(d){ return Array.isArray(d?.items) ? d.items : Array.isArray(d) ? d : []; }
export default function ApprovalBatchesPage(){ const { http } = useApi(); const api = useMemo(()=>makeBankingApi(http), [http]); const qc=useQueryClient(); const toast=useToast(); const [open,setOpen]=useState(false); const [form,setForm]=useState({ name:'', scheduledDate:'', notes:'' }); const q=useQuery({queryKey:['treasury.approvalBatches'], queryFn:()=>api.listApprovalBatches()}); const create=useMutation({ mutationFn:()=>api.createApprovalBatch(form), onSuccess:()=>{ toast.success('Approval batch created'); setOpen(false); setForm({ name:'', scheduledDate:'', notes:'' }); qc.invalidateQueries({queryKey:['treasury.approvalBatches']}); }, onError:(e)=>toast.error(e?.response?.data?.error || e.message) }); const act=useMutation({ mutationFn: async ({fn,id})=>api[fn](id), onSuccess:()=>{ qc.invalidateQueries({queryKey:['treasury.approvalBatches']}); toast.success('Action completed'); }, onError:(e)=>toast.error(e?.response?.data?.error || e.message) }); const rows=rowsOf(q.data); return <><PageHeader title="Payment Approval Batches" subtitle="Approve payment runs and bank transfers together." actions={<Button onClick={()=>setOpen(true)}>New batch</Button>} /><ContentCard><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-text-muted"><th className="py-2">Batch no</th><th>Name</th><th>Scheduled date</th><th>Status</th><th className="text-right">Items</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="py-2"><Link className="text-blue-600 hover:underline" to={ROUTES.paymentApprovalBatchDetail(r.id)}>{r.batch_no}</Link></td><td>{r.name}</td><td>{String(r.scheduled_date || '').slice(0,10)}</td><td>{r.status}</td><td className="text-right">{r.item_count ?? 0}</td><td className="text-right space-x-2">{r.status==='draft' && <Button size="sm" onClick={()=>act.mutate({fn:'submitApprovalBatch', id:r.id})}>Submit</Button>}{['draft','submitted'].includes(r.status) && <Button size="sm" variant="secondary" onClick={()=>act.mutate({fn:'approveApprovalBatch', id:r.id})}>Approve</Button>}</td></tr>)}{!rows.length && <tr><td colSpan={6} className="py-3 text-text-muted">No approval batches yet.</td></tr>}</tbody></table></div></ContentCard><Modal open={open} title="Create approval batch" onClose={()=>setOpen(false)} footer={<div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={()=>create.mutate()} disabled={create.isLoading}>{create.isLoading?'Creating...':'Create'}</Button></div>}><div className="grid gap-4"><Input label="Batch name" value={form.name} onChange={(e)=>setForm(s=>({...s,name:e.target.value}))} /><Input label="Scheduled date" type="date" value={form.scheduledDate} onChange={(e)=>setForm(s=>({...s,scheduledDate:e.target.value}))} /><Textarea label="Notes" value={form.notes} onChange={(e)=>setForm(s=>({...s,notes:e.target.value}))} /></div></Modal></>; }
