import React, { useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useApi } from '../../../shared/hooks/useApi.js';
import { makeBankingApi } from '../api/banking.api.js';
import { PageHeader } from '../../../shared/components/layout/PageHeader.jsx';
import { ContentCard } from '../../../shared/components/layout/ContentCard.jsx';
import { Button } from '../../../shared/components/ui/Button.jsx';
import { useToast } from '../../../shared/components/ui/Toast.jsx';
function money(v){ return Number(v||0).toLocaleString(); }
export default function BankTransferDetailPage(){ const { id } = useParams(); const { http } = useApi(); const api = useMemo(()=>makeBankingApi(http), [http]); const qc = useQueryClient(); const toast = useToast(); const q = useQuery({ queryKey:['treasury.bankTransfer', id], queryFn:()=>api.getBankTransfer(id) }); const act = useMutation({ mutationFn: async (fn)=>api[fn](id), onSuccess:()=>{ qc.invalidateQueries({queryKey:['treasury.bankTransfer', id]}); qc.invalidateQueries({queryKey:['treasury.bankTransfers']}); toast.success('Action completed'); }, onError:(e)=>toast.error(e?.response?.data?.error || e.message) }); const r=q.data || {}; return <><PageHeader title={`Bank Transfer ${r.code || ''}`} subtitle={r.memo || 'Review and post the transfer.'} actions={<div className="flex gap-2">{r.status==='draft' && <Button onClick={()=>act.mutate('submitBankTransfer')}>Submit</Button>}{['draft','submitted'].includes(r.status) && <Button variant="secondary" onClick={()=>act.mutate('approveBankTransfer')}>Approve</Button>}{r.status==='approved' && <Button onClick={()=>act.mutate('postBankTransfer')}>Post</Button>}</div>} /><ContentCard><div className="grid md:grid-cols-2 gap-4 text-sm"><div className="flex justify-between border rounded-lg p-3"><span>Status</span><strong>{r.status || '—'}</strong></div><div className="flex justify-between border rounded-lg p-3"><span>Transfer date</span><strong>{String(r.transfer_date || '').slice(0,10) || '—'}</strong></div><div className="flex justify-between border rounded-lg p-3"><span>From bank</span><strong>{r.from_bank_account_code || '—'}</strong></div><div className="flex justify-between border rounded-lg p-3"><span>To bank</span><strong>{r.to_bank_account_code || '—'}</strong></div><div className="flex justify-between border rounded-lg p-3"><span>Amount</span><strong>{money(r.amount)}</strong></div><div className="flex justify-between border rounded-lg p-3"><span>Fee amount</span><strong>{money(r.fee_amount)}</strong></div><div className="flex justify-between border rounded-lg p-3"><span>Reference</span><strong>{r.reference || '—'}</strong></div><div className="flex justify-between border rounded-lg p-3"><span>Journal entry</span><strong>{r.journal_entry_id || '—'}</strong></div></div></ContentCard></>; }
