export const qk = {
  me: ['me'],
  meOrganizations: ['me', 'organizations'],
  orgMe: ['org', 'me'],
  users: ['users'],
  user: (id) => ['users', id],
  roles: ['roles'],
  role: (id) => ['roles', id],
  permissions: ['permissions'],
  roleMatrix: ['roles', 'matrix'],
  rolePermissions: (id) => ['roles', id, 'permissions'],
  settingsList: (qs) => ['settings', qs],
  apiKeys: ['apiKeys'],
  dimensionRules: (qs) => ['dimensionSecurity', qs],
  notifications: (qs) => ['notifications', qs],
  approvalsInbox: (qs) => ['approvalsInbox', qs],
  utilitiesErrors: (qs) => ['utilitiesErrors', qs],
  utilitiesClientLogs: (qs) => ['utilitiesClientLogs', qs],
  healthSystem: ['healthSystem'],
  scheduledTasks: ['scheduledTasks'],
  scheduledTaskRuns: (code, qs) => ['scheduledTaskRuns', code, qs],
  i18nLocales: ['i18nLocales'],
  i18nMessages: (locale) => ['i18nMessages', locale],
  a11yStatus: ['a11yStatus'],
  releaseInfo: ['releaseInfo'],
  testsList: ['testsList']
};
