export const qk = {
  me: ['me'],
  meOrganizations: ['me', 'organizations'],
  orgMe: ['org', 'me'],
  users: ['users'],
  user: (id) => ['users', id],
  roles: ['roles'],
  role: (id) => ['roles', id],
  permissions: ['permissions'],
  roleMatrix: ['roles', 'matrix'],
  rolePermissions: (id) => ['roles', id, 'permissions'],
  settingsList: (qs) => ['settings', qs],
  apiKeys: ['apiKeys'],
  dimensionRules: (qs) => ['dimensionSecurity', qs],
  notifications: (qs) => ['notifications', qs],
  approvalsInbox: (qs) => ['approvalsInbox', qs],
  utilitiesErrors: (qs) => ['utilitiesErrors', qs],
  utilitiesClientLogs: (qs) => ['utilitiesClientLogs', qs],
  healthSystem: ['healthSystem'],
  scheduledTasks: ['scheduledTasks'],
  scheduledTaskRuns: (code, qs) => ['scheduledTaskRuns', code, qs],
  i18nLocales: ['i18nLocales'],
  i18nMessages: (locale) => ['i18nMessages', locale],
  a11yStatus: ['a11yStatus'],
  releaseInfo: ['releaseInfo'],
  testsList: ['testsList']
,
  // Phase 5
  partners: (qs) => ['partners', qs ?? {}],
  partner: (id) => ['partners', id],
  partnerCreditPolicy: (id) => ['partners', id, 'creditPolicy'],

  paymentTerms: ['paymentConfig', 'paymentTerms'],
  paymentMethods: ['paymentConfig', 'paymentMethods'],
  paymentSettings: ['paymentConfig', 'paymentSettings'],

  invoices: (qs) => ['invoices', qs ?? {}],
  invoice: (id) => ['invoices', id],

  bills: (qs) => ['bills', qs ?? {}],
  bill: (id) => ['bills', id],

  customerReceipts: (qs) => ['customerReceipts', qs ?? {}],
  customerReceipt: (id) => ['customerReceipts', id],

  vendorPayments: (qs) => ['vendorPayments', qs ?? {}],
  vendorPayment: (id) => ['vendorPayments', id],

  creditNotes: (qs) => ['creditNotes', qs ?? {}],
  creditNote: (id) => ['creditNotes', id],

  debitNotes: (qs) => ['debitNotes', qs ?? {}],
  debitNote: (id) => ['debitNotes', id],

  quotations: (qs) => ['quotations', qs ?? {}],
  quotation: (id) => ['quotations', id],

  salesOrders: (qs) => ['salesOrders', qs ?? {}],
  salesOrder: (id) => ['salesOrders', id],

  purchaseRequisitions: (qs) => ['purchaseRequisitions', qs ?? {}],
  purchaseRequisition: (id) => ['purchaseRequisitions', id],

  purchaseOrders: (qs) => ['purchaseOrders', qs ?? {}],
  purchaseOrder: (id) => ['purchaseOrders', id],

  goodsReceipts: (qs) => ['goodsReceipts', qs ?? {}],
  goodsReceipt: (id) => ['goodsReceipts', id],

  expenses: (qs) => ['expenses', qs ?? {}],
  expense: (id) => ['expenses', id],

  pettyCash: (qs) => ['pettyCash', qs ?? {}],
  pettyCashItem: (id) => ['pettyCash', id],

  advances: (qs) => ['advances', qs ?? {}],
  advance: (id) => ['advances', id],

  returns: (qs) => ['returns', qs ?? {}],
  returnItem: (id) => ['returns', id],

  refunds: (qs) => ['refunds', qs ?? {}],
  refund: (id) => ['refunds', id],

  collectionsQueue: (qs) => ['collections', 'queue', qs ?? {}],
  collectionsQueuePartner: (partnerId, qs) => ['collections', 'queue', partnerId, qs ?? {}],
  collectionsCases: (qs) => ['collections', 'cases', qs ?? {}],
  dunningTemplates: ['collections', 'dunning', 'templates'],
  dunningRules: ['collections', 'dunning', 'rules'],
  dunningRuns: ['collections', 'dunning', 'runs'],
  dunningRun: (id) => ['collections', 'dunning', 'runs', id],

  disputeReasonCodes: ['disputes', 'reasonCodes'],
  disputes: (qs) => ['disputes', qs ?? {}],
  dispute: (id) => ['disputes', id],

  writeoffReasonCodes: ['writeoffs', 'reasonCodes'],
  writeoffSettings: ['writeoffs', 'settings'],
  writeoffs: (qs) => ['writeoffs', qs ?? {}],
  writeoff: (id) => ['writeoffs', id],

  paymentPlans: (qs) => ['paymentPlans', qs ?? {}],
  paymentPlan: (id) => ['paymentPlans', id],

  reportArAging: (qs) => ['reports', 'ar', 'aging', qs ?? {}],
  reportArOpenItems: (qs) => ['reports', 'ar', 'openItems', qs ?? {}],
  reportArCustomerStatement: (qs) => ['reports', 'ar', 'customerStatement', qs ?? {}],
  reportApAging: (qs) => ['reports', 'ap', 'aging', qs ?? {}],
  reportApOpenItems: (qs) => ['reports', 'ap', 'openItems', qs ?? {}],
  reportApVendorStatement: (qs) => ['reports', 'ap', 'vendorStatement', qs ?? {}],
  reportTaxVatSummary: (qs) => ['reports', 'tax', 'vatSummary', qs ?? {}],
  reportTaxVatReturn: (qs) => ['reports', 'tax', 'vatReturn', qs ?? {}],
  reportTaxReturns: (qs) => ['reports', 'tax', 'returns', qs ?? {}],
  reportTaxTransactions: (qs) => ['reports', 'tax', 'transactions', qs ?? {}],
  reportTaxReconciliation: (qs) => ['reports', 'tax', 'reconciliation', qs ?? {}],
  reportTaxDiagnostics: (qs) => ['reports', 'tax', 'diagnostics', qs ?? {}],
  taxAdjustments: (qs) => ['tax', 'adjustments', qs ?? {}],
  withholdingDashboard: (qs) => ['tax', 'withholding', 'dashboard', qs ?? {}],
  withholdingOpenItems: (qs) => ['tax', 'withholding', 'openItems', qs ?? {}],
  withholdingRemittances: (qs) => ['tax', 'withholding', 'remittances', qs ?? {}],
  withholdingRemittance: (id) => ['tax', 'withholding', 'remittances', id],
  withholdingCertificates: (qs) => ['tax', 'withholding', 'certificates', qs ?? {}],
  withholdingCertificate: (id) => ['tax', 'withholding', 'certificates', id],
  // Phase 6 — Assets
  assetCategories: ['assets', 'categories'],
  assetCategory: (id) => ['assets', 'categories', id],
  fixedAssets: (qs) => ['assets', 'fixedAssets', qs ?? {}],
  fixedAsset: (id) => ['assets', 'fixedAssets', id],
  depreciationSchedules: (qs) => ['assets', 'depreciation', 'schedules', qs ?? {}],
  depreciationSchedule: (id) => ['assets', 'depreciation', 'schedules', id],
  depreciationPreview: (periodId) => ['assets', 'depreciation', 'preview', periodId],

  // Phase 6 — Inventory
  inventoryCategories: ['inventory', 'categories'],
  inventoryCategory: (id) => ['inventory', 'categories', id],
  inventoryUnits: ['inventory', 'units'],
  inventoryItems: ['inventory', 'items'],
  inventoryItem: (id) => ['inventory', 'items', id],
  inventoryWarehouses: ['inventory', 'warehouses'],
  inventoryTransactions: (qs) => ['inventory', 'transactions', qs ?? {}],
  inventoryTransaction: (id) => ['inventory', 'transactions', id],
  inventoryCostMethod: ['inventory', 'transactions', 'costMethod'],
  stockCounts: (qs) => ['inventory', 'stockCounts', qs ?? {}],
  stockCount: (id) => ['inventory', 'stockCounts', id],
  inventoryValuationReport: (qs) => ['inventory', 'reports', 'valuation', qs ?? {}],
  inventoryMovementsReport: (qs) => ['inventory', 'reports', 'movements', qs ?? {}],
  inventoryBins: (qs) => ['inventory', 'bins', qs ?? {}],
  inventoryReservations: (qs) => ['inventory', 'reservations', qs ?? {}],
  inventoryAvailability: (warehouseId, itemId) => ['inventory', 'availability', warehouseId, itemId],
  inventoryTransfers: (qs) => ['inventory', 'transfers', qs ?? {}],
  inventoryTransfer: (id) => ['inventory', 'transfers', id],
  inventoryBatches: (qs) => ['inventory', 'traceability', 'batches', qs ?? {}],
  inventorySerials: (qs) => ['inventory', 'traceability', 'serials', qs ?? {}],
  inventoryReorderSettings: (qs) => ['inventory', 'reorder', 'settings', qs ?? {}],
  inventoryReorderSuggestions: (qs) => ['inventory', 'reorder', 'suggestions', qs ?? {}],

  // Phase 8 — Compliance
  ifrs16Settings: ['compliance', 'ifrs16', 'settings'],
  ifrs16Leases: (qs) => ['compliance', 'ifrs16', 'leases', qs ?? {}],
  ifrs16Lease: (id) => ['compliance', 'ifrs16', 'leases', id],
  ifrs16LeaseSchedule: (leaseId) => ['compliance', 'ifrs16', 'lease', leaseId, 'schedule'],
  ifrs16LeaseAssets: (leaseId) => ['compliance', 'ifrs16', 'lease', leaseId, 'assets'],
  ifrs16LeasePayments: (leaseId, qs) => ['compliance', 'ifrs16', 'lease', leaseId, 'payments', qs ?? {}],
  ifrs16LeaseModifications: (leaseId) => ['compliance', 'ifrs16', 'lease', leaseId, 'modifications'],
  ifrs16LeaseEvents: (leaseId, qs) => ['compliance', 'ifrs16', 'lease', leaseId, 'events', qs ?? {}],
  ifrs16LeasePostingLedger: (leaseId) => ['compliance', 'ifrs16', 'lease', leaseId, 'postingLedger'],
  ifrs16Dashboard: (qs) => ['compliance', 'ifrs16', 'dashboard', qs ?? {}],
  ifrs16Disclosures: (qs) => ['compliance', 'ifrs16', 'disclosures', qs ?? {}],

  ifrs15Settings: ['compliance', 'ifrs15', 'settings'],
  ifrs15Contracts: (qs) => ['compliance', 'ifrs15', 'contracts', qs ?? {}],
  ifrs15Contract: (id) => ['compliance', 'ifrs15', 'contracts', id],
  ifrs15ContractSchedule: (id) => ['compliance', 'ifrs15', 'contracts', id, 'schedule'],
  ifrs15ContractCosts: (id) => ['compliance', 'ifrs15', 'contracts', id, 'costs'],

  ias12Settings: ['compliance', 'ias12', 'settings'],
  ias12Authorities: ['compliance', 'ias12', 'authorities'],
  ias12RateSets: ['compliance', 'ias12', 'rateSets'],
  ias12RateSetLines: (rateSetId) => ['compliance', 'ias12', 'rateSets', rateSetId, 'lines'],
  ias12TempDiffCategories: ['compliance', 'ias12', 'tempDiffCategories'],
  ias12TempDifferences: (qs) => ['compliance', 'ias12', 'tempDifferences', qs ?? {}],
  ias12DeferredTaxRuns: (qs) => ['compliance', 'ias12', 'deferredTaxRuns', qs ?? {}],
  ias12DeferredTaxRun: (runId) => ['compliance', 'ias12', 'deferredTaxRuns', runId],

  ifrs9Settings: ['compliance', 'ifrs9', 'settings'],
  ifrs9Models: ['compliance', 'ifrs9', 'models'],
  ifrs9Runs: (qs) => ['compliance', 'ifrs9', 'runs', qs ?? {}],
  ifrs9Run: (runId) => ['compliance', 'ifrs9', 'runs', runId],
  coaAccounts: (qs) => ['coa', 'accounts', qs ?? {}],

  printingTemplates: (qs) => ['printing', 'templates', qs ?? {}],
  printingTemplateAssignments: ['printing', 'assignments'],
  printingPreview: (documentType, documentId, templateId) => ['printing', 'preview', documentType, documentId, templateId ?? null],

};
